import {
	checkRateLimit,
	getClientIp,
	htmlResponse,
	incrementRateLimit,
	storeOAuthSession,
	validateState,
} from '@cc-wf-studio-connectors/shared';
import { errorTemplate, successTemplate } from './templates.js';

/**
 * Environment bindings for the callback handler
 */
export interface CallbackEnv {
	OAUTH_SESSIONS: KVNamespace;
	RATE_LIMIT: KVNamespace;
}

/**
 * Handle Slack OAuth callback
 *
 * This endpoint receives the authorization code from Slack after user
 * authorizes the app. It stores the code in KV for the VSCode extension
 * to poll and retrieve.
 *
 * Query params:
 * - code: Authorization code from Slack
 * - state: Session ID generated by VSCode extension
 *
 * @param request - Incoming request
 * @param env - Environment bindings
 * @returns HTML response (success or error page)
 */
export async function handleSlackCallback(request: Request, env: CallbackEnv): Promise<Response> {
	const url = new URL(request.url);
	const code = url.searchParams.get('code');
	const state = url.searchParams.get('state');

	// Check for Slack error response
	const error = url.searchParams.get('error');
	if (error) {
		const errorDescription = url.searchParams.get('error_description') ?? 'Unknown error';
		return htmlResponse(errorTemplate(`Slack authorization failed: ${errorDescription}`), 400);
	}

	// Validate required parameters
	if (!code) {
		return htmlResponse(errorTemplate('Missing authorization code'), 400);
	}

	if (!validateState(state)) {
		return htmlResponse(errorTemplate('Invalid or missing session state'), 400);
	}

	// Rate limiting
	const clientIp = getClientIp(request);
	const rateLimitResult = await checkRateLimit(env.RATE_LIMIT, clientIp, 'callback');

	if (!rateLimitResult.allowed) {
		return htmlResponse(errorTemplate('Too many requests. Please try again later.'), 429);
	}

	await incrementRateLimit(env.RATE_LIMIT, clientIp, 'callback');

	// Store the authorization code in KV
	try {
		await storeOAuthSession(env.OAUTH_SESSIONS, 'slack', state, code, state, clientIp);
	} catch (err) {
		console.error('Failed to store OAuth session:', err);
		return htmlResponse(errorTemplate('Failed to process authorization. Please try again.'), 500);
	}

	// Return success page
	return htmlResponse(successTemplate());
}
