import {
	checkRateLimit,
	getClientIp,
	incrementRateLimit,
	jsonResponse,
	type PollResponse,
	retrieveAndDeleteOAuthSession,
	validateSessionId,
	withCors,
} from '@cc-wf-studio-connectors/shared';

/**
 * Environment bindings for the poll handler
 */
export interface PollEnv {
	OAUTH_SESSIONS: KVNamespace;
	RATE_LIMIT: KVNamespace;
}

/**
 * Handle poll request from VSCode extension
 *
 * This endpoint is polled by the VSCode extension to check if the user
 * has completed the OAuth authorization. Once the code is retrieved,
 * it is deleted from KV (one-time use).
 *
 * Query params:
 * - session: Session ID generated by VSCode extension
 *
 * @param request - Incoming request
 * @param env - Environment bindings
 * @returns JSON response with poll status
 */
export async function handleSlackPoll(request: Request, env: PollEnv): Promise<Response> {
	const url = new URL(request.url);
	const sessionId = url.searchParams.get('session');

	// Validate session ID
	if (!validateSessionId(sessionId)) {
		const response: PollResponse = {
			status: 'expired',
			message: 'Invalid session ID',
		};
		return withCors(jsonResponse(response, 400));
	}

	// Rate limiting
	const clientIp = getClientIp(request);
	const rateLimitResult = await checkRateLimit(env.RATE_LIMIT, clientIp, 'poll');

	if (!rateLimitResult.allowed) {
		const response: PollResponse = {
			status: 'expired',
			message: 'Too many requests. Please try again later.',
		};
		return withCors(jsonResponse(response, 429));
	}

	await incrementRateLimit(env.RATE_LIMIT, clientIp, 'poll');

	// Try to retrieve the session
	try {
		const session = await retrieveAndDeleteOAuthSession(env.OAUTH_SESSIONS, 'slack', sessionId);

		if (session) {
			// Session found - return the code
			const response: PollResponse = {
				status: 'success',
				code: session.code,
			};
			return withCors(jsonResponse(response, 200));
		}

		// Session not found - either not completed yet or expired
		const response: PollResponse = {
			status: 'pending',
			message: 'Authorization not completed yet',
		};
		return withCors(jsonResponse(response, 404));
	} catch (err) {
		console.error('Failed to retrieve OAuth session:', err);
		const response: PollResponse = {
			status: 'expired',
			message: 'Failed to retrieve session',
		};
		return withCors(jsonResponse(response, 500));
	}
}
