/**
 * Session ID validation
 *
 * Session IDs are generated by VSCode extension using UUID v4 or
 * base64url encoded random bytes. This regex allows:
 * - Length: 21-43 characters
 * - Characters: alphanumeric, underscore, hyphen
 */
const SESSION_ID_REGEX = /^[a-zA-Z0-9_-]{21,43}$/;

/**
 * Validate session ID format
 *
 * @param sessionId - Session ID to validate
 * @returns true if valid format
 */
export function validateSessionId(sessionId: string | null | undefined): sessionId is string {
	if (!sessionId) return false;
	if (sessionId.length < 21 || sessionId.length > 43) return false;
	return SESSION_ID_REGEX.test(sessionId);
}

/**
 * Validate state parameter (same format as session ID)
 *
 * @param state - State parameter to validate
 * @returns true if valid format
 */
export function validateState(state: string | null | undefined): state is string {
	return validateSessionId(state);
}
